on:
  pull_request:
jobs:
  archlinux:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm make parallel wget cmake ninja mill dtc verilator git llvm clang lld protobuf antlr4 python autoconf automake python-yaml
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: work around https://github.com/actions/checkout/issues/760
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Coursier Cache
        uses: coursier/cache-action@v5
      - name: Init
        run: |
          make init
      - name: Patch
        run: |
          make update-patches
          make patch
      - name: Check Mill Compile
        run: make compile
      - name: Check Sanity
        run: make test
